name: Deploy
on:
  push:
    branches: master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D "/dev/null" "$HOME/.ssh/key"
          echo "${{ secrets.deploy }}" > "$HOME/.ssh/key"
      - name: Clone Project
        uses: actions/checkout@v4
      - name: Test Build
        run: |
          python -m pip install build
          python -m build
      - name: Build at server
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no notabot@nakidai.ru -t "cd src && sh ../deploy"
