name: Deploy
on:
  push:
    branches: master
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D "/dev/null" "$HOME/.ssh/key"
          echo "${{ secrets.deploy }}" > "$HOME/.ssh/key"
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Clone project
        uses: actions/checkout@v4
      - name: Build
        run: docker buildx build -t notabot .
      - name: Export
        run: docker save notabot | xz > notabot.txz
      - name: Push
        run: scp -i "$HOME/.ssh/key" notabot.txz notabot@nakidai.ru:notabot.txz
      - name: Post Export
        run: rm notabot.txz
      - name: Post Setup SSH
        run: rm "$HOME/.ssh/key"
  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D "/dev/null" "$HOME/.ssh/key"
          echo "${{ secrets.deploy }}" > "$HOME/.ssh/key"
      - name: Run deploy script
        run: ssh -i "$HOME/.ssh/key" -o StrictHostKeyChecking=no notabot@nakidai.ru -t "sh deploy"
      - name: Post Setup SSH
        run: rm "$HOME/.ssh/key"
