name: Deploy
on:
  workflow_run:
    workflows: [Test]
    types: [Completed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Setup SSH
        run: |
          install -m 600 -D "/dev/null" "$HOME/.ssh/key"
          echo "${{ secrets.deploy }}" > "$HOME/.ssh/key"
      - name: Run deploy script
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no notabot@nakidai.ru -t "cd src && sh ../deploy"
